# Generated by Django 3.0.7 on 2020-12-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0005_auto_20201017_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='CourseNum',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='CourseID',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='CourseName',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='Program',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
